/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false apps/web/worker-configuration.d.ts` (hash: af4a902dd9876f30854560284c09ae3e)
interface __BaseEnv_Env {
  ANALYTICS_DB: D1Database;
  ANALYTICS_LIMITER: RateLimit;
  IMAGES: ImagesBinding;
  ASSETS: Fetcher;
  SEOJING_BACKEND_ARTICLE_API_ORIGIN: "https://api.seojing.com";
  SEOJING_BACKEND_ARTICLE_SLUGS: "study/effective-typescript/day5";
  SEOJING_OPS_ACCESS_ISSUER: "https://black-flower-54e3.cloudflareaccess.com";
  SEOJING_OPS_ACCESS_AUD: "cc9c0008c5374255745bff7e21e3ba75e0cd67e87d732e76eed1d88452def1cd";
  SEOJING_CF_RUM_SITE_TAG: "2e22d864bfba4ea282d33749b30d517f";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "SEOJING_BACKEND_ARTICLE_API_ORIGIN"
      | "SEOJING_BACKEND_ARTICLE_SLUGS"
      | "SEOJING_OPS_ACCESS_ISSUER"
      | "SEOJING_OPS_ACCESS_AUD"
      | "SEOJING_CF_RUM_SITE_TAG"
    >
  > {}
}
